POST http://localhost:8083/api/v1/user HTTP/1.1
content-type: application/json

{
    "first_name": "Mirceass",
    "last_name": "Blebea",
    "age": 31
}

###

POST http://localhost:8081/api/v1/order HTTP/1.1
content-type: application/json

{
    "coffee_id": "mocha_small",
    "user_id": "432ffa77-24de-4afe-a3e0-311ff7461f6d",
    "amount": 120
}

###

@user_id=432ffa77-24de-4afe-a3e0-311ff7461f6d
GET http://localhost:8081/api/v1/orders?user_id={{ user_id }} HTTP/1.1

###

GET http://localhost:8081/api/v1/menu HTTP/1.1

###

GET http://localhost:8082/api/v1/bonus?user_id={{user_id}} HTTP/1.1
@user_id=432ffa77-24de-4afe-a3e0-311ff7461f6d